main: logan.pickpocket.main.PickPocket
name: PickPocket
version: v1.0-pre
author: TTG_TRE
commands:
  pickpocket:
    aliases: pp
    description: Display help information for PickPocket.
    permission: pickpocket.use