main: logan.pickpocket.main.PickPocket
name: PickPocket
version: v0.9.9
author: TTG_TRE
commands:
  pickpocket:
    description: Display help information for PickPocket.
    permission: pickpocket.use